global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: nexusstock

scrape_configs:
  - job_name: nexusstock-app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:3000
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: nexusstock

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
